services:
  servicedeskform:
    build:
      context: ServiceDeskForm
    image: nssa/servicedeskform:latest
    container_name: ServiceDeskForm
    restart: unless-stopped
    ports: 
      - '51813:51813'
    networks:
      - servicedeskform
    # volumes:
      # - /data/docker_bindmount_volumes/servicedesk_webhook:/code/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.72.119.23:51813/servicedesk/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
  servicedeskform:
    name: servicedeskform
    driver: bridge
